services:
  traefik:
    image: traefik:v3.0
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=malk_777@outlook.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/letsencrypt

  fastapi:
    build: ./server
    restart: always
    env_file: ./server/.env
    environment:
      - DATABASE_URL=sqlite:////app/data/my_database.db
    volumes:
      - db_data:/app/data
    expose:
      - "8000"

  client:
    build: ./client
    restart: always
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`ottawaautocentre.ca`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
    depends_on:
      - fastapi

volumes:
  traefik_data:
  db_data:
