services:
  fastapi:
    build: ./server
    restart: always
    env_file: ./server/.env
    environment:
      - DATABASE_URL=sqlite:////app/data/my_database.db
    volumes:
      - db_data:/app/data
    expose:
      - "8000"

  client:
    build: ./client
    restart: always
    ports:
      - "127.0.0.1:3001:80"
    depends_on:
      - fastapi

volumes:
  db_data:
