"""init migration

Revision ID: a97dcad1a4c8
Revises: 5178ff3c3b5a
Create Date: 2025-12-09 12:03:46.826310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97dcad1a4c8'
down_revision: Union[str, Sequence[str], None] = '5178ff3c3b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create new items table
    op.create_table(
        'items',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('category', sa.String(), index=True, nullable=False),
        sa.Column('name', sa.String(), unique=True, nullable=False),
        sa.Column('mode', sa.String(), default='single'),
        sa.Column('new', sa.Integer(), default=0),
        sa.Column('used', sa.Integer(), default=0),
    )

    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # drop table 'items'
    op.drop_table('items')

    # ### end Alembic commands ###
