"""create items table

Revision ID: bc28c2dbb7bc
Revises: 
Create Date: 2025-12-09 12:30:09.219980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc28c2dbb7bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_threshold_id'), table_name='threshold')
    # op.drop_table('threshold')
    # op.drop_table('logs')
    # op.drop_index(op.f('ix_tires_id'), table_name='tires')
    # op.drop_table('tires')
    # op.drop_table('users')
    # ### end Alembic commands ###

    op.create_table(
        'items',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('category', sa.String(), index=True, nullable=False),
        sa.Column('name', sa.String(), unique=True, nullable=False),
        sa.Column('mode', sa.String(), default='single'),
        sa.Column('new', sa.Integer(), default=0),
        sa.Column('used', sa.Integer(), default=0),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###







